modLoader = "javafml"
loaderVersion = "[39,)"
license = "${mod_license}"
#issueTrackerURL=""

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL = ""
displayURL = "${mod_url}"
logoFile = "${mod_id}.png"
#credits = ""
authors = "${mod_author}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"
